version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: bookshelf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookshelf
    ports: 
      - "3306:3306"